### ISSUE TITLE
Suspected of not supporting codeberg?

### ISSUE THREAD

**Issue by linser233** [FT-Fetters/DockerPull#19]
Can be replicated in both Windows and Linux environments.

$ java -jar DockerPull-web-1.3.1.jar pull codeberg.org/forgejo/forgejo:9.0.3-rootless
➤ - starting pull codeberg.org/forgejo/forgejo:9.0.3-rootless
➤ - using proxy: null
Exception in thread "main" java.lang.NullPointerException
        at com.heybcat.docker.pull.core.registry.RegistryHelper.getPullToken(RegistryHelper.java:45)
        at com.heybcat.docker.pull.core.pull.RegistryImagePuller.authPullToken(RegistryImagePuller.java:84)
        at com.heybcat.docker.pull.core.pull.RegistryImagePuller.pull(RegistryImagePuller.java:51)
        at com.heybcat.docker.pull.CommandStartup.handleCommand(CommandStartup.java:52)
        at com.heybcat.docker.pull.CommandStartup.main(CommandStartup.java:26)

**Comment by linser233** [comment]
Suspected to have a network issue with my local device
